frequency: 20
sensor_timeout: 0.5
# two_d_mode: true
print_diagnostics: false #echo the /diagnostics_agg topic for details

pose0: "none" # Add in the launch file
pose0_config: [true, true, true,
              true, true, true,
              false, false, false,
              false, false, false,
              false, false, false]

world_frame: map
map_frame: map
# odom_frame: odom
base_link_frame: base_link
