

remap: 
       frequency: 50
       topic_name_subscriber: /vicon/jackal3/jackal3
       topic_name_publisher: /vicon/jackal3_mapped
       publish_pose: true
       publish_pose_with_covariance_stamped: true
